name: polkadot-parachain
title: Polkadot Parachain
base: core24
adopt-info: polkadot-parachain
summary: Polkadot - A multi-chain framework for better blockchain interoperability
license: GPL-3.0-with-GCC-exception
contact: info@dwellir.com
issues: https://github.com/dwellir-public/snap-polkadot/issues
source-code: https://github.com/dwellir-public/snap-polkadot/
website: https://www.dwellir.com
grade: stable
confinement: strict


platforms:
  amd64:

description: |
  Polkadot is a multi-chain framework that enables interoperability and scalability for multiple blockchains.
  See: https://github.com/paritytech/polkadot-sdk
  
  Hardware requirements can be found here: https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#standard-hardware

  Start the service with 'sudo snap start polkadot-parachain'

  Check logs from the Polkadot service with 'snap logs polkadot-parachain -f'

  Supported configuration options for the snap:
  
  service-args [default=--base-path=$SNAP_COMMON/polkadot_base --name=<hostname>]
  For available arguments see https://github.com/paritytech/polkadot-sdk
  The value set here will be passed to the Polkadot binary with a few exceptions listed below. 
  * --name defaults to the systems hostname the first time the snap is installed.
  * --base-path is always set by the snap to `$SNAP_COMMON/polkadot_base` and is not allowed to be configured.

  endure [default=false]
  If true the Polkadot service will not be restarted after a snap refresh.
  Note that the Polkadot service will still be restarted as the result of changing service-args, etc.

  Use this when restarts should be avoided e.g. when running a validator.

  Example config for running on Polkadot with an RPC endpoint on port 9933:

  sudo snap set polkadot-parachain service-args="--name=foobar --chain=polkadot --rpc-port=9933"

parts:
  polkadot-parachain:
    plugin: rust
    source: https://github.com/paritytech/polkadot-sdk.git
    source-tag: polkadot-stable2506-1
    source-depth: 1
    build-packages:
      - build-essential
      - libssl-dev
      - git 
      - clang
      - llvm-dev
      - libclang-dev 
      - pkg-config
      - protobuf-compiler
    override-pull: |
      rustup install stable
      rustup default stable
      rustup update nightly
      rustup component add rust-src
      rustup target add wasm32-unknown-unknown
      rustup target add wasm32-unknown-unknown --toolchain nightly
      rustup target add wasm32v1-none --toolchain stable
      rustup target add wasm32v1-none --toolchain stable-x86_64-unknown-linux-gnu
      craftctl default
      craftctl set version="polkadot-stable2506-1-$(git rev-parse --short HEAD)"
    override-build: |
      cargo build --release
      install -D target/release/polkadot-parachain $SNAPCRAFT_PART_INSTALL/bin/polkadot-parachain
      install -D target/release/polkadot-execute-worker $SNAPCRAFT_PART_INSTALL/bin/polkadot-execute-worker
      install -D target/release/polkadot-prepare-worker $SNAPCRAFT_PART_INSTALL/bin/polkadot-prepare-worker
    prime:
      - bin/polkadot-parachain
      - bin/polkadot-execute-worker
      - bin/polkadot-prepare-worker

  wrappers:
    plugin: dump
    source-type: local
    source: .
    stage:
      - wrappers/
  
  utils:
      plugin: dump
      source-type: local
      source: .
      stage:
        - utils/

apps:
  polkadot-parachain:
    command: wrappers/start-polkadot.bash
    daemon: simple
    install-mode: disable
    refresh-mode: endure
    restart-condition: on-failure
    plugs:
      - network
      - network-bind
      - removable-media
      - system-observe
      - hardware-observe
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

  cli:
    command: bin/polkadot-parachain
    plugs:
      - network
      - home
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
